from __future__ import annotations

import re


NORTH_AMERICA_LOCATION_STOPWORDS = {
    # Countries and broad regions.
    "america",
    "can",
    "canada",
    "canadian",
    "mex",
    "mexico",
    "mx",
    "usa",
    "u s",
    "u s a",
    "us",
    "united states",
    # Canadian provinces and territories.
    "ab",
    "alberta",
    "bc",
    "british columbia",
    "mb",
    "manitoba",
    "nb",
    "new brunswick",
    "nl",
    "newfoundland",
    "newfoundland labrador",
    "northwest territories",
    "nova scotia",
    "ns",
    "nt",
    "nu",
    "nunavut",
    "on",
    "ont",
    "ontario",
    "pei",
    "prince edward island",
    "qc",
    "quebec",
    "saskatchewan",
    "sk",
    "yukon",
    "yt",
    # US states, district, and common territories.
    "ak",
    "al",
    "alabama",
    "alaska",
    "ar",
    "arkansas",
    "az",
    "ca",
    "california",
    "co",
    "colorado",
    "connecticut",
    "ct",
    "dc",
    "de",
    "delaware",
    "district columbia",
    "fl",
    "florida",
    "ga",
    "georgia",
    "gu",
    "guam",
    "hawaii",
    "hi",
    "ia",
    "id",
    "idaho",
    "il",
    "illinois",
    "in",
    "indiana",
    "iowa",
    "ks",
    "kansas",
    "kentucky",
    "ky",
    "la",
    "louisiana",
    "ma",
    "maine",
    "maryland",
    "massachusetts",
    "md",
    "me",
    "mi",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "mn",
    "mo",
    "montana",
    "mp",
    "ms",
    "mt",
    "nc",
    "nd",
    "ne",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "nh",
    "nj",
    "nm",
    "north carolina",
    "north dakota",
    "northern mariana islands",
    "nv",
    "ny",
    "oh",
    "ohio",
    "ok",
    "oklahoma",
    "or",
    "oregon",
    "pa",
    "pennsylvania",
    "pr",
    "puerto rico",
    "rhode island",
    "ri",
    "sc",
    "sd",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "tn",
    "tx",
    "ut",
    "utah",
    "va",
    "vermont",
    "virgin islands",
    "virginia",
    "vt",
    "wa",
    "washington",
    "west virginia",
    "wi",
    "wisconsin",
    "wv",
    "wy",
    "wyoming",
    # Mexico federal entities and common abbreviations.
    "aguascalientes",
    "baja california",
    "baja california sur",
    "campeche",
    "chiapas",
    "chihuahua",
    "ciudad de mexico",
    "coahuila",
    "colima",
    "durango",
    "edomex",
    "guanajuato",
    "guerrero",
    "hidalgo",
    "jalisco",
    "michoacan",
    "morelos",
    "nayarit",
    "nuevo leon",
    "oaxaca",
    "puebla",
    "queretaro",
    "quintana roo",
    "san luis potosi",
    "sinaloa",
    "sonora",
    "tabasco",
    "tamaulipas",
    "tlaxcala",
    "veracruz",
    "yucatan",
    "zacatecas",
    # Major city/location tokens commonly appended to card statement names.
    "atlanta",
    "austin",
    "baltimore",
    "boston",
    "brooklyn",
    "calgary",
    "charlotte",
    "chicago",
    "columbus",
    "dallas",
    "denver",
    "detroit",
    "edmonton",
    "fort worth",
    "halifax",
    "hamilton",
    "houston",
    "indianapolis",
    "jacksonville",
    "kansas city",
    "las vegas",
    "los angeles",
    "miami",
    "mississauga",
    "montreal",
    "nashville",
    "new orleans",
    "new york",
    "north york",
    "ottawa",
    "philadelphia",
    "phoenix",
    "portland",
    "quebec city",
    "regina",
    "sacramento",
    "san antonio",
    "san diego",
    "san francisco",
    "san jose",
    "saskatoon",
    "scarborough",
    "seattle",
    "st louis",
    "surrey",
    "toronto",
    "vancouver",
    "victoria",
    "washington",
    "winnipeg",
}


BANK_DESCRIPTOR_STOPWORDS = {
    "branch",
    "card",
    "contactless",
    "debit",
    "inc",
    "interac",
    "llc",
    "ltd",
    "merchant",
    "misc",
    "online",
    "payment",
    "pos",
    "purchase",
    "retail",
    "terminal",
    "visa",
}


TERM_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    (r"\bapps?\b", "app "),
    (r"\bautomotive\b", "auto "),
    (r"\bbkry\b", "bakery"),
    (r"\bboulangerie\b", "bakery"),
    (r"\bcafe\b", "cafe"),
    (r"\bcaffe\b", "cafe"),
    (r"\bcoff\b", "coffee"),
    (r"\bconv\b", "convenience"),
    (r"\bdin(?:e|r)?\b", "diner"),
    (r"\bdspnsry\b", "dispensary"),
    (r"\belec\b", "electronics"),
    (r"\bfuel\b", "gas"),
    (r"\bgroc(?:ery)?\b", "grocery"),
    (r"\bmkt\b", "market"),
    (r"\bmobil\b", "mobile"),
    (r"\bpharm(?:acy)?\b", "pharmacy"),
    (r"\brest\b", "restaurant"),
    (r"\bres\b", "restaurant"),
    (r"\brstrnt\b", "restaurant"),
    (r"\bsmke\b", "smoke"),
    (r"\bsuper\s?mar\w*\b", "supermarket"),
    (r"\bsuper\s*$", "supermarket"),
    (r"\bsvc\b", "service"),
    (r"\btelecom\b", "phone"),
)


MERCHANT_ALIAS_EXPANSION = {
    "abc fine wine": "abc fine wine",
    "ambrosia natural foods": "ambrosia natural foods",
    "ambrosia thornh": "ambrosia thornh",
    "ambrosia vaughan": "ambrosia vaughan",
    "apple com bill": "apple com bill",
    "bcl liquor": "bcl liquor",
    "canna cabana": "canna cabana",
    "foodbasics": "food basics",
    "google youtube": "youtube",
    "la fitness": "la fitness",
    "lcbo": "lcbo",
    "planet fitness": "planet fitness",
    "saq": "saq",
    "the beer store": "beer store",
    "tokyo smoke": "tokyo smoke",
    "value buds": "value buds",
    "wholefds": "whole foods",
}


MERCHANT_CATEGORY_OVERRIDES: dict[str, tuple[str, float]] = {
    "ambrosia natural foods": ("groceries", 0.97),
    "ambrosia thornh": ("groceries", 0.96),
    "ambrosia vaughan": ("groceries", 0.96),
    "ambrosia newmarket": ("groceries", 0.96),
    "ambrosia avenue": ("groceries", 0.96),
    "ambrosia leslieville": ("groceries", 0.96),
    "arzon supermarket": ("groceries", 0.94),
    "food basics": ("groceries", 0.96),
    "foodbasics": ("groceries", 0.96),
    "khorak super": ("groceries", 0.94),
    "khorak supermarket": ("groceries", 0.94),
    "kourosh super": ("groceries", 0.94),
    "orange mart": ("groceries", 0.92),
}


CATEGORY_ALIAS_EXPANSION = {
    "auto": "car maintenance",
    "auto repair": "car maintenance",
    "car": "car maintenance",
    "dining": "restaurant",
    "food": "restaurant",
    "fuel": "gas",
    "home goods": "home",
    "medical": "health",
    "pharmacy": "health",
    "rideshare": "transport",
    "streaming": "subscriptions",
    "transit": "transport",
}


CATEGORY_KEYWORD_EXPANSION: dict[str, tuple[str, ...]] = {
    "groceries": (
        "99 ranch",
        "aldi",
        "albertsons",
        "asian market",
        "basha",
        "big y",
        "bravo supermarket",
        "california market",
        "city market",
        "couche tard",
        "cub foods",
        "fiesta mart",
        "food 4 less",
        "food basics",
        "foodbasics",
        "foodland",
        "fortinos",
        "fred meyer",
        "giant eagle",
        "giant food",
        "grocery outlet",
        "h e b",
        "heb",
        "hannaford",
        "iga",
        "ingles",
        "instacart",
        "jewel osco",
        "kroger",
        "maxi",
        "meijer",
        "mercado",
        "mercado latino",
        "piggly wiggly",
        "price chopper",
        "publix",
        "ralphs",
        "real canadian superstore",
        "safeway",
        "save on foods",
        "savealot",
        "schnucks",
        "shoprite",
        "smart and final",
        "sprouts",
        "stater bros",
        "stop and shop",
        "super c",
        "superama",
        "superstore",
        "trader joe",
        "vons",
        "wegmans",
        "weis markets",
        "winco",
        "winn dixie",
    ),
    "restaurant": (
        "a and w",
        "arbys",
        "bagel shop",
        "bar burrito",
        "baskin robbins",
        "blaze pizza",
        "booster juice",
        "boston pizza",
        "buffalo wild wings",
        "burger king",
        "cactus club",
        "cheesecake factory",
        "chick fil a",
        "chipotle",
        "cinnabon",
        "dairy queen",
        "dennys",
        "doordash",
        "dq grill",
        "earls kitchen",
        "five guys",
        "grubhub",
        "harveys",
        "ihop",
        "in n out",
        "in n out burger",
        "jack in the box",
        "jersey mikes",
        "kelseys",
        "little caesars",
        "mandarin restaurant",
        "mary browns",
        "mcdonald",
        "mcdonalds",
        "montanas",
        "olive garden",
        "panera",
        "panda express",
        "popeyes",
        "qsr",
        "raising canes",
        "red lobster",
        "shake shack",
        "skip dishes",
        "skip the dishes",
        "starbelly",
        "sweetgreen",
        "swiss chalet",
        "taco bell",
        "taco time",
        "wendys",
        "wingstop",
    ),
    "cafe": (
        "aroma espresso",
        "biggby coffee",
        "caribou coffee",
        "coffee bean",
        "dutch bros",
        "dunkin",
        "peets coffee",
        "philz coffee",
        "second cup",
        "starbucks",
        "tims",
    ),
    "gas": (
        "76 gas",
        "ampm",
        "arco",
        "bp gas",
        "caseys general",
        "chevron",
        "circle k",
        "costco gas",
        "esso",
        "exxon",
        "flying j",
        "husky",
        "irving oil",
        "marathon",
        "mobil",
        "onroute",
        "petro canada",
        "petrocan",
        "pilot travel",
        "qt gas",
        "quiktrip",
        "racetrac",
        "sams club fuel",
        "sheetz",
        "shell",
        "speedway",
        "sunoco",
        "texaco",
        "valero",
        "wawa",
    ),
    "transport": (
        "amtrak",
        "bart",
        "bike share",
        "bixi",
        "bluebikes",
        "brampton transit",
        "caltrain",
        "car2go",
        "cta",
        "goco",
        "go transit",
        "lime ride",
        "mbta",
        "metrolinx",
        "mta",
        "nj transit",
        "opus",
        "septa",
        "stm",
        "translink",
        "via rail",
        "wmata",
        "york region transit",
        "yrt",
        "zipcar",
    ),
    "travel": (
        "air canada",
        "alaska airlines",
        "american airlines",
        "booking com",
        "delta airlines",
        "expedia",
        "hilton",
        "hyatt",
        "marriott",
        "southwest airlines",
        "united airlines",
        "vrbo",
        "westjet",
    ),
    "health": (
        "cvs",
        "familiprix",
        "jean coutu",
        "london drugs",
        "pharmaprix",
        "rexall",
        "rite aid",
        "the medicine shoppe",
        "uniprix",
        "walgreens",
        "walk in clinic",
    ),
    "smoking": (
        "canna cabana",
        "cookies cannabis",
        "dutch love",
        "e cig",
        "fire and flower",
        "nova cannabis",
        "spiritleaf",
        "stiiizy",
        "tokyo smoke",
        "value buds",
    ),
    "alcohol": (
        "abc fine wine",
        "bcl liquor",
        "bevmo",
        "liquor depot",
        "saq",
        "specs wines",
        "the beer store",
        "total wine",
    ),
    "beauty": (
        "great clips",
        "massage envy",
        "sport clips",
        "ulta",
    ),
    "clothing": (
        "abercrombie",
        "adidas",
        "aritzia",
        "banana republic",
        "fashion nova",
        "gap",
        "lululemon",
        "marshalls",
        "nike",
        "old navy",
        "ross dress",
        "shein",
        "tj maxx",
        "under armour",
    ),
    "home": (
        "bed bath",
        "canadian tire",
        "homesense",
        "lowes",
        "lowe s",
        "menards",
        "wayfair",
    ),
    "electronics": (
        "apple store",
        "canada computers",
        "fido device",
        "micro center",
        "microsoft store",
        "newegg",
        "source electronics",
        "staples",
    ),
    "shopping": (
        "costco wholesale",
        "dollar general",
        "family dollar",
        "five below",
        "giant tiger",
        "miniso",
        "sams club",
        "target",
    ),
    "subscriptions": (
        "adobe",
        "apple com bill",
        "audible",
        "canva",
        "crave",
        "disney plus",
        "dropbox",
        "google storage",
        "google youtube",
        "hbo max",
        "hulu",
        "icloud",
        "kindle",
        "microsoft 365",
        "netflix",
        "paramount plus",
        "peacock",
        "plex",
        "prime video",
        "siriusxm",
        "spotify",
        "youtube premium",
    ),
    "entertainment": (
        "amc theatres",
        "cineplex",
        "cinemark",
        "eventbrite",
        "gamestop",
        "nintendo",
        "regal cinemas",
        "steam games",
        "ticketmaster",
    ),
    "car maintenance": (
        "advance auto",
        "auto parts",
        "autozone",
        "car wash",
        "discount tire",
        "jiffy lube",
        "midas",
        "mr lube",
        "napa auto",
        "oil changers",
        "pep boys",
    ),
    "pets": (
        "chewy",
        "pet valu",
        "petco",
    ),
    "shipping": (
        "dhl",
        "usps",
    ),
    "utilities": (
        "bc hydro",
        "con edison",
        "direct energy",
        "duke energy",
        "epcor",
        "hydro quebec",
        "hydro one",
        "national grid",
        "pg and e",
        "pseg",
    ),
    "phone": (
        "att wireless",
        "cricket wireless",
        "metro by t mobile",
        "mint mobile",
        "t mobile",
        "verizon",
        "virgin plus",
    ),
    "internet": (
        "comcast",
        "cox communications",
        "shaw internet",
        "spectrum",
        "videotron",
        "xfinity",
    ),
    "insurance": (
        "allstate",
        "geico",
        "progressive",
        "state farm",
    ),
}


SEMANTIC_CATEGORY_MARKER_EXPANSION = CATEGORY_KEYWORD_EXPANSION | {
    "groceries": (*CATEGORY_KEYWORD_EXPANSION["groceries"], "bodega", "marketplace grocery"),
    "restaurant": (*CATEGORY_KEYWORD_EXPANSION["restaurant"], "eatery", "taqueria"),
    "gas": (*CATEGORY_KEYWORD_EXPANSION["gas"], "gas bar", "service station"),
    "smoking": (*CATEGORY_KEYWORD_EXPANSION["smoking"], "head shop", "smoke and vape"),
}


GOOGLE_PLACE_TYPE_CATEGORY_EXPANSION: dict[str, tuple[str, float]] = {
    "airport": ("travel", 0.82),
    "bus_stop": ("transport", 0.82),
    "car_repair": ("car maintenance", 0.88),
    "car_wash": ("car maintenance", 0.86),
    "convenience_store": ("groceries", 0.82),
    "department_store": ("shopping", 0.84),
    "electric_vehicle_charging_station": ("transport", 0.82),
    "liquor_store": ("alcohol", 0.92),
    "movie_theater": ("entertainment", 0.88),
    "night_club": ("entertainment", 0.76),
    "performing_arts_theater": ("entertainment", 0.84),
    "smoke_shop": ("smoking", 0.9),
    "tobacco_shop": ("smoking", 0.9),
}


def normalize_category_signal_text(value: str) -> str:
    normalized = value.lower().replace("&", " and ")
    normalized = re.sub(r"[*#:_./\\-]+", " ", normalized)
    for pattern, replacement in TERM_REPLACEMENTS:
        normalized = re.sub(pattern, replacement, normalized)
    normalized = re.sub(r"\b\d+[a-z]*\b", " ", normalized)
    normalized = re.sub(r"[^a-z0-9 ]+", " ", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip()
    return normalized


def phrase_matches_normalized_text(phrase: str, normalized_text: str) -> bool:
    normalized_phrase = normalize_category_signal_text(phrase)
    if not normalized_phrase or not normalized_text:
        return False

    return f" {normalized_phrase} " in f" {normalized_text} "


def match_merchant_category_override(description: str) -> tuple[str, float, str] | None:
    normalized_description = normalize_category_signal_text(description)
    for phrase, (category, confidence) in sorted(
        MERCHANT_CATEGORY_OVERRIDES.items(),
        key=lambda item: len(item[0]),
        reverse=True,
    ):
        if phrase_matches_normalized_text(phrase, normalized_description):
            return category, confidence, phrase

    return None


def strip_location_and_bank_noise_tokens(value: str) -> str:
    normalized = normalize_category_signal_text(value)
    tokens = [
        token
        for token in normalized.split()
        if token not in BANK_DESCRIPTOR_STOPWORDS and token not in NORTH_AMERICA_LOCATION_STOPWORDS
    ]
    return re.sub(r"\s+", " ", " ".join(tokens)).strip()
